### ISSUE TITLE
Regarding the crop size on Cityscapes

### ISSUE THREAD

**Issue by hsfzxjy** [shipra25jain/ESSNet#2]
I've found this line in `main.py` https://github.com/shipra25jain/ESSNet/blob/main/main.py#L140 . Seems that the codebase will use square crop for Cityscapes, which is inconsistent with the paper (400 x 800). Should I modify manually to (400, 800)?

**Comment by shipra25jain** [comment]
Yes, thank you for pointing that out. All cityscapes experiments are done with 400*800 crop size. i will make the correction in code.

**Comment by hsfzxjy** [comment]
Thank you very much.
