### ISSUE TITLE
About the training settings on COCO+LVIS

### ISSUE THREAD

**Issue by hsfzxjy** [shipra25jain/ESSNet#6]
Hi, 

I am trying to train ESSNet on COCO+LVIS, but seemingly could not find the settings of some parameters (B, k, d) in your paper. Could you give some advice?

Thank you.

**Comment by shipra25jain** [comment]
@hsfzxjy ,
we will update the arxiv file this week, with additional information for COCO+LVIS experiments.

Thanks

**Comment by shipra25jain** [comment]
@hsfzxjy , we have now updated our arxiv paper at https://arxiv.org/pdf/2012.07489.pdf
You will find more details about COCO+LVIS dataset. Also, let me know if you have any doubt regarding the building of COCO+LVIS dataset.

**Comment by hsfzxjy** [comment]
@shipra25jain Thank you for your clarification! The settings in paper is clear enough and I will try them in the following days.
